### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by cpressland** [EverythingSmartHome/everything-presence-one#10]
Would it be possible to get a CHANGELOG.md or use GitHub Releases for firmware updates? The frequent updates are great, but it'd be nice to know what each update changes to judge if it's worth me grabbing the device and plugging it in (Unless OTA updates are a thing and I've simply not noticed).

**Comment by EverythingSmartHome** [comment]
Yes planning to add a page to the user guide for that along with a bunch more information and configuration stuff - very short on time at the moment but it is on my to do list for sure.

OTA updates are a thing, you just need to enable Safe Mode for the device in Home Assistant before hitting the update wireless option.
