### ISSUE TITLE
Devices from bridged Vera not showing in Everything Presents One

### ISSUE THREAD

**Issue by Burnell** [EverythingSmartHome/everything-presence-one#102]
Automation only devices showing are Phillips Hue. I can control all of them in an automation. None of my bridged Vera devices show. All the Vera devices are in Home assistant dashboard (36).
Hope I can get this solved.
Thanks Burnell

**Comment by EverythingSmartHome** [comment]
Vera isn't a platform we support at the moment and I have no way of testing this unfortunately
