### ISSUE TITLE
EP1 loses connectivity to home wireless after each firmware update

### ISSUE THREAD

**Issue by dnedeltchev** [EverythingSmartHome/everything-presence-one#104]
Every time I update the firmware, EP1 loses the WiFi settings and the AP is enabled. So every time I update the firmware I have to connect to the AP, configure the WiFi and EP1 is back online. Is this expected behaviour or I've done something wrong?

**Comment by EverythingSmartHome** [comment]
What method are you using to update?

**Comment by dnedeltchev** [comment]
I update Esphome and then update the sensor directly in home assistant.
________________________________

**Comment by dnedeltchev** [comment]
User error! The SSID was incorrect in the esphome secrets file. Thank you Lewis for the great support!
