### ISSUE TITLE
Expansion Header Details

### ISSUE THREAD

**Issue by GadgetUK** [EverythingSmartHome/everything-presence-one#12]
Can you provide details on the pinout of the expansion header.

**Comment by EverythingSmartHome** [comment]
Yes when time permits. They are written on the underside of the board meantime.

**Comment by GadgetUK** [comment]
Great thanks. 
To help others out here's the info

![IMG_20230106_123725285](https://user-images.githubusercontent.com/1688999/211014783-36f9302f-c075-4eea-96ba-50e5190d65ee.jpg)
