### ISSUE TITLE
mmWave On Latency too low

### ISSUE THREAD

**Issue by JRascagneres** [EverythingSmartHome/everything-presence-one#121]
The mmWave On latency maximum was reduced to 2s which is far too low for me. I have trickle vents in my windows and when there is a very large gust of wind outside some of this gets through and moves the chain for my blinds. It barely does but this results in the chain swinging a tiny amount for a few seconds. This means I need a relatively high mmWave On latency in order to tackle this. Please can we get the original maximum value back?

**Comment by rofo69** [comment]
You can change the yaml file from the repo yourself if you want to make the value higher again.
However, by making it higher than a couple of seconds, you've baically removed the main advantage of a mmwave sensor, which is to detectvery small (and brief) movements. So setting a high value will end up with the sensor going to a clear state if you are sitting still.

Also, iirc, there is some target range code in the current beta code which could allow you to screen out the chain if you know its distance from the mmwave sensor. (if I understand this correctly, if you set (say) a target range for the first zone to 1-3meters, and the second zone to 5-8 meters, anything in between would be ignored).
