### ISSUE TITLE
Zone Support (in style of Aqara FP2)

### ISSUE THREAD

**Issue by SchoolGuy** [EverythingSmartHome/everything-presence-one#126]
I understand that the sensor already has support for distance zones (which is very very nice) but I would love if this could be extended so one could map physical areas of a room.

As an example how I would imagine it I have taken the liberty to attach a screenshot of the product page of the FP2 from Aqara.

![Screenshot_2023-12-16-21-05-54-30_3aea4af51f236e4932235fdada7d1643_1.jpg](https://github.com/EverythingSmartHome/everything-presence-one/assets/15035141/a506b279-6fac-46b0-b621-089bd3a28203)

**Comment by EverythingSmartHome** [comment]
This question has been asked probably more than 200 times by now 😅 it is unfortunately not possible with this sensor, the firmware on the mmwave sensor itself does not expose this kind of information.
