### ISSUE TITLE
Occupancy entity reset to Clear but PIR and/or mmWave entities still showing as Detected

### ISSUE THREAD

**Issue by alexhk90** [EverythingSmartHome/everything-presence-one#128]
Using the beta/pre-release firmware (v1.3.0b), I've noticed a couple of times where the Occupancy entity has (correctly) changed to "Clear", but the mmWave and/or PIR entities stay as "Detected" until the next time there is actually motion detected (at which point they correctly change to "Clear" when the motion has stopped). 

See attached screenshots for an example: 
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/13845698/75a3c8d9-02fe-4505-9f89-66d1eea19e27)
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/13845698/01fb1d10-796a-4c84-b1b5-418b7a1238fd)

**Comment by EverythingSmartHome** [comment]
Please let me know if this is still an issue in the newer versions
