### ISSUE TITLE
Can we retrieve input on GPIO headers to have another link of the data in case of Wifi failure #konnected.io

### ISSUE THREAD

**Issue by Zwordi** [EverythingSmartHome/everything-presence-one#131]
Hi,

I’m going to setup my 3 EP1 in my ceiling and as it will be done through an multi-wired section I was wondering if I could through the GPIO get an "contact" about the mwave/PIR in order to have it connected into something like konnected.io.

Thanks

**Comment by EverythingSmartHome** [comment]
You could buy creating your own config and using the spare GPIO pins to simulate outputs using the GPIO output: https://esphome.io/components/output/gpio.html

When the PIR or mmWave turns on then you turn the output on and when it's off you turn the output off
