### ISSUE TITLE
mmWave LED sometimes on after Reboot/Power-cycle/Firmware upgrade

### ISSUE THREAD

**Issue by bakerkj** [EverythingSmartHome/everything-presence-one#137]
Physical mmWave LED sometimes on after Reboot/Power-cycle/Firmware upgrade even though home assistant switch indicates that the LED is off.

**Comment by jokerigno** [comment]
+1 on this.

I found a workaround turn on esp 32 led wait few sec and then turn them off

**Comment by TB-SE** [comment]
+1 same issue

**Comment by TNTPro** [comment]
I'm having the same issue. Also, when the mmWave light is on, the sensitivity of the mmWave seems to be bad, as my room lights keeps turning off, like I'm not there.

**Comment by IneedAnewNick** [comment]
Yep same issue here too

**Comment by marcinwasilewski** [comment]
Isn't the LED on until the config (sensor sensitivity settings etc) is written to flash ?

**Comment by IneedAnewNick** [comment]
This only happens on one of my three changing a setting does turn it off but as I say only one out of three does this.

**Comment by EverythingSmartHome** [comment]
Can you please try the latest version? I added a quick couple of lines which I hope will help to ensure that the sensor is started after boot. The new version is v1.1.10, you may need to flash over USB using the user guide if you still have the old cached

**Comment by bakerkj** [comment]
@EverythingSmartHome I'll give it a try. Thanks!!

**Comment by TB-SE** [comment]
> The new version is v1.1.10, you may need to flash over USB using the user guide if you still have the old cached

I can't see the new version on Github. The latest I see is 1.1.9

**Comment by EverythingSmartHome** [comment]
> > The new version is v1.1.10, you may need to flash over USB using the user guide if you still have the old cached
> 
> I can't see the new version on Github. The latest I see is 1.1.9

It's not listed as a Github release, but it is there. Just update via the ESPHome add-on or the user guide

**Comment by bakerkj** [comment]
@EverythingSmartHome this seems to continue to occur even with the latest changes.

**Comment by EverythingSmartHome** [comment]
> @EverythingSmartHome this seems to continue to occur even with the latest changes.

I would try again if you haven't updated today, I added some further changes that most definitely resolve this from my own testing.

**Comment by bakerkj** [comment]
@EverythingSmartHome I didn't see that you'd pushed more changes. I'll give it another go. 

Thanks!

**Comment by jokerigno** [comment]
USB is the only way to update latest fw?

**Comment by danielsvane** [comment]
Im also unsure how to best update. Do I have to connect it to a PC, or can I do it through esphome integration? This is what it looks like from my esphome tab. Im scared to click the button, since its working fine (the red LED is just constantly on).

![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/36197/d3660e39-9da6-483b-a584-0666ffeeb87a)

**Comment by olympia** [comment]
I would be interested in the best update approach too (also in order to keep the settings).

**Comment by emdekext** [comment]
Same problem here, everytime after an esphome firmware flash (update for instance) the mmwave LED stays on, but is reported as being switched of, and the mmwave sensor is reported as switched on but does not report any presence/movement. Only after writing settings to the mmwave sensor flash it starts to function again.
