### ISSUE TITLE
Unable to turn off mWave sensor Status LED

### ISSUE THREAD

**Issue by theseus-powers** [EverythingSmartHome/everything-presence-one#158]
Recently updated to the latest EPO Firmware ability to turn off mWave status led is gone now.

it looks like some of the code was removed in the firmware:
```
- platform: binary
    name: mmWave LED
    restore_mode: RESTORE_DEFAULT_OFF
    output: mmwave_led_output
    entity_category: config
    disabled_by_default: True
```
Is this what controlled the mmWave led?

**Comment by EverythingSmartHome** [comment]
Whoops, didn't mean to remove that! Have restored it now in https://github.com/EverythingSmartHome/everything-presence-one/pull/159
