### ISSUE TITLE
Is https://shop.everythingsmart.io/en-no/pages/contact working?

### ISSUE THREAD

**Issue by dooniem** [EverythingSmartHome/everything-presence-one#160]
I wrote a message on the contact form regarding a troublesome Presence One, 2 weeks ago(?). Since I didn't get any confirmation e-mail or the like, I am just wondering if my message got through, if you or someone are reading the inquiries?
Should I post my error messages here, even though I believe it's faulty hardware rather than code?

PS. I'm totally fine with an answer similar to: "Will look at it when have the time". I just wonder if it has reached you...

**Comment by EverythingSmartHome** [comment]
Yes the contact page works - if we haven't yet replied then it may have been marked as spam or somehow we just missed it, in which case my apologies. If you would like to send it again via the contact page I will look out for it and get back to you ASAP.
