### ISSUE TITLE
bluetooth_proxy: active for the new bluetooth firmware install?

### ISSUE THREAD

**Issue by townsmcp** [EverythingSmartHome/everything-presence-one#162]
Today I noticed there are additional options on the firmware install page (https://everythingsmarthome.github.io/everything-presence-one/updating.html) for beta or stable firmware with bluetooth proxy. @EverythingSmartHome My question is, once we have flashed the EP1 with one of these firmware versions with bluetooth capability, do we still need to add the following to ESP Home config for the given device?

```
bluetooth_proxy:
  active: true
```

**Comment by EverythingSmartHome** [comment]
No you don't need to add that, it's all done in the config
