### ISSUE TITLE
ESPHome Updates

### ISSUE THREAD

**Issue by jasonmadigan** [EverythingSmartHome/everything-presence-one#163]
After performing an ESPHome update (after an HA prompt) for the EP1, the device goes into a strange/broken state:

- Sensors go unavailable
- I get a `Integration requires reconfiguration` notification
- Clicking `Reconfigure` for the device gives an error:
- - `The ESPHome device Everything Presence One 283acc enabled transport encryption or changed the encryption key. Please enter the updated key. You can find it in the ESPHome Dashboard or in your device configuration.`
- - I do not know what the key should be.

<img width="604" alt="Screenshot 2024-03-04 at 17 21 15" src="https://github.com/EverythingSmartHome/everything-presence-one/assets/4467/d44caaea-18cc-425c-ba49-4e181943740e">

The only way to get things back and working again is to re-flash.

**Comment by jasonmadigan** [comment]
Odd this isn't that graceful.

I found the key via ESPHome's UI. Edit the device, you'll find it in this block:

```yaml
api:
  encryption:
    key: xxx
```

**Comment by EverythingSmartHome** [comment]
This is an ESPHome configuration thing, most likely when you have pressed adopt to the config in the ESPHome dashboard, it adds an encryption key (and tells you) which Home Assistant isn't aware of (if adopted after it was added to HA) - go into the ESPHome dashboard, edit the config and you should see the key listed
