### ISSUE TITLE
Duplicate and Triplicate sensors on same device

### ISSUE THREAD

**Issue by IanMajor12** [EverythingSmartHome/everything-presence-one#174]
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/83884948/d1b7816d-89cc-4496-8afd-1b9acf728b94)

The one in the kitchen has it 3x for each sensor.

Not sure how I did this, and had to go through and delete all the Entities for the device.

Is there a better way to clean this up, or do a reset?
Did I do something silly?

Seems like it was the change from sensor.humidity to ep1_kitchen_humidity so probably when I renamed the device?

**Comment by EverythingSmartHome** [comment]
Sorry I missed this, but yes it's likely from renaming at some point and then updating. You can click the entities and delete from the UI.
