### ISSUE TITLE
Meaning of "mmWave Range Reduced" and "mmWave Sustain Sensitivity" for SEN0609 in the documentation

### ISSUE THREAD

**Issue by Mincka** [EverythingSmartHome/everything-presence-one#178]
Hello,

I did not find anywhere the meaning of the settings called `mmWave Range Reduced` and `mmWave Sustain Sensitivity` that were introduced with the support of SEN0609.

The default value is "0.8 m" for `mmWave Range Reduced` and "7" for `mmWave Sustain Sensitivity`.

I could guess that "Sustain Sensitivity" is the capability to keep tracking an object more reliably, but for the other setting, I have no idea.

Would it be possible to update the tuning guide and the documentation with these new settings?

Thank you.

**Comment by pablogiganti** [comment]
Hi, I would also appreciate a bit of explanation please

**Comment by EverythingSmartHome** [comment]
Added now here: https://everythingsmarthome.github.io/everything-presence-one/Home%20Assistant/home-assistant-entities.html#distance-and-sensitivity-sen0609

Hope that helps!
