### ISSUE TITLE
Enabling BLE Kills the device

### ISSUE THREAD

**Issue by Veldkornet** [EverythingSmartHome/everything-presence-one#182]
If I switch from everything-presence-one.yaml to everything-presence-one-ble.yaml (and re-flash via USB.... or any other method), the device fails to boot. 
When plugged in via USB, these were the latest logs I can get (note that even the browser hangs at this point:

![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/10297361/f93e2d5d-04bf-4bcf-b0c2-150b6574b193)

**Comment by EverythingSmartHome** [comment]
What happens if you flash directly from the user guide instead?

**Comment by Veldkornet** [comment]
> What happens if you flash directly from the user guide instead?

What do you mean from the user guide? Can you point me to it?

Currently, I just opened ESPHome, edited the device settings "package" section to use ble instead of the normal one.

**Comment by EverythingSmartHome** [comment]
Yes that's right

**Comment by Veldkornet** [comment]
> Yes that's right

Yes, it seems to work now! Not sure why though, I compared the two configs in ESP home and they look the same...

**Comment by Kummallinen** [comment]
I had the same issue today, the trick seems to be to do a "Clean Build Files" after changing the packages config to point to the ble one, but before building & installing it
