### ISSUE TITLE
OTA Platforms - the easy way

### ISSUE THREAD

**Issue by neildsb** [EverythingSmartHome/everything-presence-one#190]
Hi, is there and easy way to update with the following on ESPHome 2024.6.1?

https://next.esphome.io/changelog/2024.6.0.html#ota-platforms

**Comment by neildsb** [comment]
** update **

fixed by adding 

ota:
  platform: esphome

and update again works...leaving 'open' for a while for others in the same boat

**Comment by Dinth** [comment]
The workaround is super easy but it should be fixed upstream asap, as many people are just including code from github:
```
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
```

**Comment by EverythingSmartHome** [comment]
Yes I will fix this morning

**Comment by EverythingSmartHome** [comment]
Fixed in: https://github.com/EverythingSmartHome/everything-presence-one/pull/189
