### ISSUE TITLE
ESP32 status LED id

### ISSUE THREAD

**Issue by mcsdodo** [EverythingSmartHome/everything-presence-one#192]
Hi, can't there be an id for the [status led](https://github.com/EverythingSmartHome/everything-presence-one/blob/main/common/everything-presence-one-base.yaml#L37) so it can be controlled within esphome? My use-case is to indicate voice_assitant platform events. Or am I missing something (I'm new in esphome).

**Comment by EverythingSmartHome** [comment]
The LED is already in Home Assistant and has always been a status LED: https://github.com/EverythingSmartHome/everything-presence-one/blob/43a205cbc109c672f3ae34f8525509519cbebf3d/common/everything-presence-one-base.yaml#L43
