### ISSUE TITLE
Documentation: Editorial

### ISSUE THREAD

**Issue by dpawson** [EverythingSmartHome/everything-presence-one#194]
https://everythingsmarthome.github.io/everything-presence-one/updating.html

"First, make sure you have the EP1 connected you a USB port on your computer"

Suggest
First, make sure you have the EP1 connected 'to' a USB port on your computer

**Comment by EverythingSmartHome** [comment]
Thanks, fixed in https://github.com/EverythingSmartHome/everything-presence-one/pull/204
