### ISSUE TITLE
can´t update EP1

### ISSUE THREAD

**Issue by spereg53** [EverythingSmartHome/everything-presence-one#195]
give this error:INFO ESPHome 2024.3.1
INFO Reading configuration /config/esphome/everything-presence-one-d7249c.yaml...
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

**Comment by EverythingSmartHome** [comment]
There is no error included in the logs above, did you attach the full log?

**Comment by spereg53** [comment]
INFO ESPHome 2024.3.1
INFO Reading configuration /config/esphome/presence-one.yaml...
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

ota: [source /data/packages/405587a8/common/everything-presence-one-base.yaml:25]
  
  expected a dictionary.
  - platform: esphome

**Comment by EverythingSmartHome** [comment]
Please update your ESPHome add-on, this was added in 2024.6 but you are running ESPHome 2024.3
