### ISSUE TITLE
OTA Update to 2024.7.0 and 2024.7.1 failing

### ISSUE THREAD

**Issue by TomFrank19087** [EverythingSmartHome/everything-presence-one#208]
This applies to both EP1 and EP Lite. When updating to 2024.6.6 I had to change my config files ota:, platform: esphome to ota:, platform: http_request, and the update was successful. Both the 2024.7.0 and 2024.7.1 updates fail, claiming platform: esphome is missing (see logs below). If I revert back to platform: esphome, it fails because http_request is missing, just like iit did before the 2024.6.6 update. If I include both I get a duplicate parameter error. The complies seem to go fine, so I think there's an issue with my yaml files. Below are my yaml files and the update all logs from ESPHome. Other than the ota platform changes, I've made no other edits to the yaml files since adding the devices. Thank you.

everything-presence-one-e011a8.yaml

substitutions:
  name: everything-presence-one-e011a8
packages:
  Everything_Smart_Technologies.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false

ota:
  platform: http_request

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

everything-presence-lite-890a04.yaml

substitutions:
  name: everything-presence-lite-890a04
  friendly_name: Everything Presence Lite 890a04
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: XXX Redacted XXX

ota:
  platform: http_request

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

Logs

Updating /config/esphome/everything-presence-lite-890a04.yaml
------------------------------------------------------------

INFO ESPHome 2024.7.1
INFO Reading configuration /config/esphome/everything-presence-lite-890a04.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing everything-presence-lite-890a04 (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
|-- Improv @ 1.2.3
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/api_connection.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/api_server.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/list_entities.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/proto.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/api/user_services.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/bh1750/bh1750.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/bluetooth_proxy/bluetooth_connection.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/button/button.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble/ble.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble/ble_advertising.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble/ble_uuid.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_client/ble_characteristic.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_client/ble_client_base.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_client/ble_service.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_server/ble_characteristic.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_server/ble_descriptor.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_server/ble_server.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_server/ble_service.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/esp32_improv/esp32_improv_component.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/http_request/http_request.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/http_request/http_request_arduino.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/http_request/http_request_idf.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/http_request/ota/ota_http_request.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/http_request/update/http_request_update.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/http_request/watchdog.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/i2c/i2c.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/i2c/i2c_bus_arduino.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/i2c/i2c_bus_esp_idf.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/improv_base/improv_base.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/improv_serial/improv_serial_component.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/json/json_util.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/addressable_light.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/automation.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/esp_color_correction.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/esp_range_view.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/light_call.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/light_json_schema.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/light_output.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/light/light_state.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/logger/logger.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/logger/logger_esp32.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/logger/logger_esp8266.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/logger/logger_host.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/logger/logger_libretiny.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/logger/logger_rp2040.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/md5/md5.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/mdns/mdns_component.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/mdns/mdns_esp32.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/mdns/mdns_esp8266.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/mdns/mdns_host.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/mdns/mdns_libretiny.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/mdns/mdns_rp2040.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/network/util.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/number/automation.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/number/number.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/number/number_call.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/number/number_traits.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/ota/ota_backend.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/ota/ota_backend_arduino_libretiny.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/ota/ota_backend_arduino_rp2040.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/ota/ota_backend_esp_idf.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/output/automation.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/output/float_output.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/restart/button/restart_button.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/safe_mode/safe_mode.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/sensor/automation.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/sensor/filter.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/sensor/sensor.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/socket/bsd_sockets_impl.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/socket/lwip_raw_tcp_impl.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/socket/lwip_sockets_impl.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/socket/socket.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/status_led/light/status_led_light.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/switch/automation.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/switch/switch.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/template/binary_sensor/template_binary_sensor.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/template/number/template_number.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/template/sensor/template_sensor.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/template/switch/template_switch.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/template/text_sensor/template_text_sensor.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/text_sensor/filter.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/text_sensor/text_sensor.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_component.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_component_esp32_arduino.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_component_esp8266.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_component_esp_idf.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_component_host.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_component_libretiny.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_component_rp2040.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/uart/uart_debugger.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/update/update_entity.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/wifi/wifi_component.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/wifi/wifi_component_esp32_arduino.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/wifi/wifi_component_esp8266.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/wifi/wifi_component_esp_idf.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/wifi/wifi_component_libretiny.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/components/wifi/wifi_component_pico_w.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/application.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/component.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/component_iterator.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/controller.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/entity_base.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/helpers.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/log.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/ring_buffer.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/scheduler.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/string_ref.o
Compiling .pioenvs/everything-presence-lite-890a04/src/esphome/core/util.o
Compiling .pioenvs/everything-presence-lite-890a04/src/main.o
Linking .pioenvs/everything-presence-lite-890a04/firmware.elf
RAM:   [==        ]  17.3% (used 56732 bytes from 327680 bytes)
Flash: [========= ]  86.1% (used 1580065 bytes from 1835008 bytes)
Building .pioenvs/everything-presence-lite-890a04/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/everything-presence-lite-890a04/firmware.bin"], [".pioenvs/everything-presence-lite-890a04/firmware.elf"])
Wrote 0x1935d0 bytes to file /data/build/everything-presence-lite-890a04/.pioenvs/everything-presence-lite-890a04/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/everything-presence-lite-890a04/firmware.bin"], [".pioenvs/everything-presence-lite-890a04/firmware.elf"])
======================== [SUCCESS] Took 256.97 seconds ========================
INFO Successfully compiled program.
ERROR Cannot upload Over the Air as the ota configuration is not present or does not include platform: esphome
 [ERROR] /config/esphome/everything-presence-lite-890a04.yaml 

Updating /config/esphome/everything-presence-one-e011a8.yaml
------------------------------------------------------------

INFO ESPHome 2024.7.1
INFO Reading configuration /config/esphome/everything-presence-one-e011a8.yaml...
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing everything-presence-one-e011a8 (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
|-- Improv @ 1.2.3
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/api_connection.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/api_server.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/list_entities.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/proto.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/api/user_services.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/bh1750/bh1750.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/button/button.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/http_request/http_request.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/http_request/http_request_arduino.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/http_request/http_request_idf.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/http_request/ota/ota_http_request.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/http_request/update/http_request_update.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/http_request/watchdog.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/i2c/i2c.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/i2c/i2c_bus_arduino.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/i2c/i2c_bus_esp_idf.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/improv_base/improv_base.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/improv_serial/improv_serial_component.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/json/json_util.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/addressable_light.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/automation.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/esp_color_correction.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/esp_range_view.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/light_call.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/light_json_schema.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/light_output.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/light/light_state.o
src/esphome/components/light/light_call.cpp:11:25: warning: 'const esphome::LogString* esphome::light::color_mode_to_human(esphome::light::ColorMode)' defined but not used [-Wunused-function]
 static const LogString *color_mode_to_human(ColorMode color_mode) {
                         ^~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/logger/logger.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/logger/logger_esp32.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/logger/logger_esp8266.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/logger/logger_host.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/logger/logger_libretiny.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/logger/logger_rp2040.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/md5/md5.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/mdns/mdns_component.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/mdns/mdns_esp32.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/mdns/mdns_esp8266.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/mdns/mdns_host.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/mdns/mdns_libretiny.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/mdns/mdns_rp2040.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/network/util.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/number/automation.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/number/number.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/number/number_call.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/number/number_traits.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/ota/ota_backend.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/ota/ota_backend_arduino_libretiny.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/ota/ota_backend_arduino_rp2040.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/ota/ota_backend_esp_idf.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/output/automation.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/output/float_output.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/restart/button/restart_button.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/safe_mode/button/safe_mode_button.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/safe_mode/safe_mode.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/sensirion_common/i2c_sensirion.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/sensor/automation.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/sensor/filter.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/sensor/sensor.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/shtcx/shtcx.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/socket/bsd_sockets_impl.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/socket/lwip_raw_tcp_impl.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/socket/lwip_sockets_impl.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/socket/socket.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/status_led/light/status_led_light.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/switch/automation.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/switch/switch.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/template/binary_sensor/template_binary_sensor.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/template/number/template_number.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/template/switch/template_switch.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_component.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_component_esp32_arduino.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_component_esp8266.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_component_esp_idf.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_component_host.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_component_libretiny.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_component_rp2040.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/uart/uart_debugger.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/update/update_entity.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/wifi/wifi_component.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/wifi/wifi_component_esp32_arduino.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/wifi/wifi_component_esp8266.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/wifi/wifi_component_esp_idf.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/wifi/wifi_component_libretiny.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/components/wifi/wifi_component_pico_w.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/application.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/component.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/component_iterator.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/controller.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/entity_base.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/helpers.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/log.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/ring_buffer.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/scheduler.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/string_ref.o
Compiling .pioenvs/everything-presence-one-e011a8/src/esphome/core/util.o
Compiling .pioenvs/everything-presence-one-e011a8/src/main.o
Linking .pioenvs/everything-presence-one-e011a8/firmware.elf
RAM:   [=         ]   9.7% (used 31880 bytes from 327680 bytes)
Flash: [=====     ]  51.4% (used 944073 bytes from 1835008 bytes)
Building .pioenvs/everything-presence-one-e011a8/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/everything-presence-one-e011a8/firmware.bin"], [".pioenvs/everything-presence-one-e011a8/firmware.elf"])
Wrote 0xf8180 bytes to file /data/build/everything-presence-one-e011a8/.pioenvs/everything-presence-one-e011a8/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/everything-presence-one-e011a8/firmware.bin"], [".pioenvs/everything-presence-one-e011a8/firmware.elf"])
======================== [SUCCESS] Took 180.13 seconds ========================
INFO Successfully compiled program.
ERROR Cannot upload Over the Air as the ota configuration is not present or does not include platform: esphome
 [ERROR] /config/esphome/everything-presence-one-e011a8.yaml 

======================== [SUMMARY] ========================
  - /config/esphome/everything-presence-lite-890a04.yaml: FAILED
  - /config/esphome/everything-presence-one-e011a8.yaml: FAILED

**Comment by EverythingSmartHome** [comment]
This isn't need it at all, it's because the config is modified from standard. To revert back to original, completely remove the OTA block as that gets pulled down from the Github as part of the package.

**Comment by TomFrank19087** [comment]
That did the trick! Both EP1 and EPLite successfully updated to the just posted 2024.7.2 update. Many thanks, Lewis!
