### ISSUE TITLE
zone creation add on - target dot doesn't move

### ISSUE THREAD

**Issue by smcdako** [EverythingSmartHome/everything-presence-one#229]
zone creation add on - target dot doesn't move, but the data in the table is moving. 
i have 4 sensors, add on appears to work for each, but then doesn't put target/s on the map.
dot sits at the top. 

Thanks

**Comment by EverythingSmartHome** [comment]
This is the EP1 repo, the EP1 doesn't support zones and doesn't work in the zone configurator
