### ISSUE TITLE
No Home Assistant how-to?

### ISSUE THREAD

**Issue by dooniem** [EverythingSmartHome/everything-presence-one#26]
My two sensors arrived today, yay!
I remember watching a Youtube video were you were saying non-HA users could expect to connect the Everything Presence One through MQTT. But being totally unfamiliar with ESPHome, I don't know where to begin?

First off, I assume it's possible to get signals without having Home Assistant running as a middleman, but maybe that's wrong?

I have found the IP of my sensors, Fing reports no open ports. As far as I understand from the documentation on ESPHome, MQTT needs to be enabled manually? I read about a ESPHome dashboard, but it's hard to reach without having Home Assistant?

I have a MQTT broker running on Docker through Synology NAS, and hope to use Homey instead of HA for handling the sensor.
But I probably need to tell the sensor the Broker IP?

There is a [ESPHome project public on the Homey app store](https://homey.app/en-us/app/nl.inversion.esphome/ESPhome/)  that was updated 2 weeks ago. They suggest port 6053 when connecting. I thought maybe that could be my "way in". Even get around using MQTT...But can't connect.
Through the console through your update-button I was able to read the log saying:
[D][api.connection:918]: homey (::FFFF:192.168.50.60): Connected successfully
[W][api.connection:083]: homey (::FFFF:192.168.50.60): Connection closed

Inside Homey I get this error: "Cannot read properties of undefined (reading 'deserializeBinary')"

I understand if you can't help with Homey specific projects for ESPHome, just thought it was helpful knowing MQTT isn't our only option. But I am grateful for any hints and paths to take to get me going (except the obvious "just use HA" of course..).
Can I use the console to open ports or enable MQTT?

**Comment by EverythingSmartHome** [comment]
You can use either MQTT as you mentioned above, or there is also the ESPHome Rest API which could work too:

MQTT: https://esphome.io/components/mqtt.html
API: https://esphome.io/web-api/index.html

Both of these options would require creating your own custom firmware for it (I don't have a Homey to test with) but if you would like to contribute the firmware then I'm happy to add it as an option for other people to install too.
