### ISSUE TITLE
mmWave LED constantly flashing

### ISSUE THREAD

**Issue by te-hb-whatever** [EverythingSmartHome/everything-presence-one#27]
This. It is constantly flashing. Changing the "mmWave LED" switch has no effect whatsoever.

**Comment by oneseventhree** [comment]
> Have you tried updating the EP1 via the online installer ? Go here: https://everythingsmarthome.github.io/everything-presence-one/updating.html and check #41 if you have issues

I just got mine and I have updated today and mine is still flashing - any ideas:
<img width="330" alt="Screenshot 2023-05-10 at 8 38 29 pm" src="https://github.com/EverythingSmartHome/everything-presence-one/assets/15043282/06db14da-3b55-466e-922e-ddfd61722f31">

This is the light:
<img width="187" alt="Screenshot 2023-05-10 at 8 39 59 pm" src="https://github.com/EverythingSmartHome/everything-presence-one/assets/15043282/348f3997-e190-4598-8179-73d296f7dbbc">

**Comment by oneseventhree** [comment]
> If you are able to join the Discord I can try and help troubleshoot what is going on here

Weirdly enough I woke up this morning and the light was off and is staying off. So I guess it’s ok for now! Thanks :)
