### ISSUE TITLE
Firmware Upgrade - Linux

### ISSUE THREAD

**Issue by reefland** [EverythingSmartHome/everything-presence-one#28]
First time trying to use ESP Home with Linux.  I think my issues is just lack of documentation on the [Updating](https://everythingsmarthome.github.io/everything-presence-one/updating.html) page.

* Upon clicking the blue [`CONNECT`] button, I get a dialog box of serial ports, but none of them have anything listed as connected.  An image of what to expect when everything is connected here would be helpful!

Best guess way to determine chip type and USB port connected too on Linux:
```
$ sudo dmesg | grep uart
 
[224037.060960] usbserial: USB Serial support registered for ch341-uart
[224037.060973] ch341 1-1:1.0: ch341-uart converter detected
[224037.061394] usb 1-1: ch341-uart converter now attached to ttyUSB0

$ lsusb | grep serial

Bus 001 Device 012: ID 1a86:7523 QinHeng Electronics CH340 serial converter
```
* Upon selecting `USB Serial (ttyUSB0)` serial port and clicking [`Connect`] button I get a message:
```
Failed to execute 'open' on 'SerialPort': Failed to open serial port.
```
---
To troubleshoot this, check the permissions of the USB device:
```
$ ls -l /dev/ttyUSB0

crw-rw---- 1 root uucp 188, 0 Mar 10 13:51 /dev/ttyUSB0
```
* Need to be a member of group `uucp` to read/write to this USB device.
* Add yourself to this group, to add myself (rich) to this group:
```
$ sudo usermod -aG uucp rich
```
* Need to logout and back in again for the new group membership to take effect
* Confirm you are a member of the group now:
```
$ groups
 
sys network power uucp lp wheel rich
```

Now access the link via Chrome, click blue [`CONNECT`] button, select   `USB Serial (ttyUSB0)` serial port and clicking [`Connect`] button and now it should be able to connect:
![image](https://user-images.githubusercontent.com/16230914/224406340-b6e8b12c-42e5-42b6-8317-0724766e33e3.png)

Success! drivers are included in the Linux kernel, I'm using kernel 6.1.12.  Just permissions prevent you from connecting to the USB device.

**Comment by EverythingSmartHome** [comment]
Glad you figured it out!
