### ISSUE TITLE
Occupancy stuck in detected when mmWave turned off while in detected state

### ISSUE THREAD

**Issue by dw01113** [EverythingSmartHome/everything-presence-one#33]
I needed to disable mmWave sensor whilst 3D printer was running in my garage as kept it detected and the lights on incorrectly, so added logic in HA to turn off mmWave sensor whilst 3D printer was running. However this did not turn off the lights as expected, on investigation after turning off the mmWave sensor it remains at it's last state, which in my case is usually "detected". This in turn kept the Occupancy sensor from switching off also. 

3 options to solve this

1. Clear the sensor somehow after issuing a  "sensorStop".
2. Add a template binary sensor which would be the "mmWave" sensor, a proxy essentially which would be set on any changes from the mmWave but could also be cleared when mmWave disabled using "publish_state".
3. Modify the logic to the Occupancy sensor to ignore the mmWave when it is disabled.

I investigated if there is any way to clear the sensor when it gets switched off and the mmWave docs didn't show anything. I was going to try the mmWave reset command after the "sensorStop" command but was unsure what this would actually do as the DFRobot wiki isn't very detailed on that. So without further investigation into option 1, option 3 seems the lowest impact change, have modified the Occupancy lambda to the following code

```
    lambda: |-
      bool newState = id(occupancy).state;
      if( id(mmwave_sensor).state)
      {
        if ( id(mmwave).state or id(pir_motion_sensor).state) {
          newState = true;
        } 
        else if (id(mmwave).state == 0 and id(pir_motion_sensor).state == 0) {
          newState = false;
        } 
      }
      else
      {
         newState = id(pir_motion_sensor).state;
      }
      return newState;
```

**Comment by EverythingSmartHome** [comment]
Thanks for the info!
