### ISSUE TITLE
mmwave false positive - sensitivity 1

### ISSUE THREAD

**Issue by neildsb** [EverythingSmartHome/everything-presence-one#35]
I am receiving many false positives on the mmWave sensor, is it faulty? I have tuned it down to sensitivity 1, the distance is 3m, off 30 sec, location in a bathroom without windows and a large mirror.....

![image](https://user-images.githubusercontent.com/91122872/225856644-18b07868-97da-4598-945f-81fe19dab997.png)

Everything_Presence_One
by Everything_Smart_Technology
Firmware: 2023.3.0 (Mar 16 2023, 11:06:07)
Hardware: 1.1.3

additional YAML in ESPHOME from stock

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  
sensor:
  - platform: wifi_signal
    name: "${room} Wi-Fi"
    update_interval: 600s

**Comment by bajarrr** [comment]
Have you tried setting the mmWave On latency to  something more than 0? I had similiar issues to what you describe before I increased that - I think 1 or 2 seconds did the trick for me.

The default for this parameter from the manufacturer of the mmWave sensor is 2.5 seconds.

**Comment by neildsb** [comment]
thanks, testing now, have turn the sensitivity back up to 7 while testing

**Comment by neildsb** [comment]
That sorted the problem, no false positives for ~30mins, maybe this needs to be a sticky FAQ @EverythingSmartHome EverythingSmartHome, I just noticed the everything-presence-one.yaml default is 1s, I must have changed it on the slider GUI at some point without understanding the consequences :-)
