### ISSUE TITLE
Light intensity bh1750 sensor fails to communicate

### ISSUE THREAD

**Issue by gregorycullen1** [EverythingSmartHome/everything-presence-one#40]
Hello!

Im having an issue with the bh1750 sensor. No data is being reported to Home Assistant and when looking at the logs, im getting the following error on boot.  

`[E][bh1750.sensor:121]: Communication with BH1750 failed!`

This has happened with both 2023.3.1 and previous firmware versions.

**Comment by EverythingSmartHome** [comment]
Hello!

Can you post the startup logs of the device?

**Comment by gregorycullen1** [comment]
Yeah for sure. 

`ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:258]: Log initialized
[C][ota:469]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][uart.arduino_esp32:077]: Setting up UART...
[    90][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[C][status_led:056]: Setting up Status LED...
[D][binary_sensor:034]: ' mmWave': Sending initial state OFF
[D][template.switch:049]:   Restored state ON
[D][switch:013]: 'mmWave Sensor' Turning ON.
[D][switch:056]: 'mmWave Sensor': Sending state ON
[D][template.switch:049]:   Restored state OFF
[D][switch:017]: 'mmWave LED' Turning OFF.
[D][switch:017]: 'mmWave Sensor' Turning OFF.
[D][switch:056]: 'mmWave Sensor': Sending state OFF
[D][switch:056]: 'mmWave LED': Sending state OFF
[D][template.switch:049]:   Restored state OFF
[D][switch:017]: 'uart_presence_output' Turning OFF.
[D][switch:017]: 'mmWave Sensor' Turning OFF.
[D][switch:056]: 'uart_presence_output': Sending state OFF
[D][template.switch:049]:   Restored state OFF
[D][switch:017]: 'uart_target_output' Turning OFF.
[D][switch:017]: 'mmWave Sensor' Turning OFF.
[D][switch:056]: 'uart_target_output': Sending state OFF
[D][number:012]: 'mmWave Distance': Sending state 315.000000
[D][number:012]: 'mmWave Off Latency': Sending state 15.000000
[D][number:012]: 'mmWave On Latency': Sending state 0.000000
[D][number:012]: 'mmWave Sensitivity': Sending state 7.000000
[C][light:036]: Setting up light 'ESP32 Status LED'...
[D][status_led:039]: 'ESP32 Status LED': Setting initital state
[D][status_led:051]: 'ESP32 Status LED': Setting state OFF
[D][light:035]: 'ESP32 Status LED' Setting:
[D][light:040]:   Color mode: 
[C][shtcx:028]: Setting up SHTCx...
[C][shtcx:056]:   Device identified: SHTC3 (0887)
[C][bh1750.sensor:041]: Setting up BH1750 ' Illuminance'...
[E][component:113]: Component bh1750.sensor was marked as failed.
[C][esp32_ble:026]: Setting up BLE...
[D][esp32_ble:042]: BLE setup complete
[D][esp32_ble_server:034]: Setting up BLE Server...
[D][esp32.preferences:113]: Saving 5 preferences to flash...
[D][esp32.preferences:142]: Saving 5 preferences to flash: 4 cached, 1 written, 0 failed
[D][uart_debug:158]: >>> "sensorStartsensorStopsensorStopsensorStop"
[D][uart_debug:158]: <<< "sensorStart\r\n"
[D][uart_debug:158]: <<< "Done\r\n"
[D][shtcx:100]: Got temperature=28.14°C humidity=34.60%
[D][sensor:127]: ' Temperature': Sending state 25.13919 °C with 1 decimals of accuracy
[D][sensor:127]: ' Humidity': Sending state 39.59625 % with 1 decimals of accuracy
[D][esp32_ble_server:071]: BLE server setup successfully
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: C8:F0:9E:EF:DB:70
[D][wifi:048]: Loaded saved wifi settings: Transporter
[D][wifi:386]: Starting scan...
[D][esp32_improv.component:201]: Setting Improv to start
[D][uart_debug:158]: <<< "leapMMW:/>"
[D][uart_debug:158]: >>> "setLedMode 1 1setUartOutput 1 0"
[D][uart_debug:158]: <<< "setLedMode 1 1\r\n"
[D][uart_debug:158]: <<< "sensor is not stopped\r\n"
[D][uart_debug:158]: <<< "Error\r\n"
[D][uart_debug:158]: <<< "leap"
[D][uart_debug:158]: >>> "setUartOutput 2 0"
[D][uart_debug:158]: <<< "MMW:/>setUartOutput 1 0\r\n"
[D][uart_debug:158]: <<< "sensor is not stopped\r\n"
[D][uart_debug:158]: <<< "Error\r\n"
[D][uart_debug:158]: <<< "leapMMW:/>setUartOutput 2 0\r\n"
[D][uart_debug:158]: <<< "sensor is not stopped\r\n"
[D][uart_debug:158]: <<< "Error\r\n"
[D][esp32_improv.component:076]: Service started!
[D][uart_debug:158]: <<< "leapMMW:/>"
[D][uart_debug:158]: >>> "saveConfigsaveConfig"
[D][uart_debug:158]: <<< "saveConfigsaveConfig\r\n"
[D][uart_debug:158]: <<< "saveConfigsaveConfig is not recognized as a CLI command\r\n"
[D][uart_debug:158]: <<< "Error\r\n"
[D][uart_debug:158]: <<< "leapMMW:/>"
[D][uart_debug:158]: >>> "saveConfig"
[D][uart_debug:158]: <<< "saveConfig\r\n"
[D][uart_debug:158]: <<< "sensor is not stopped\r\n"
[D][uart_debug:158]: <<< "Done\r\n"
[D][uart_debug:158]: <<< "leapMMW:/>"
[D][wifi:401]: Found networks:
[I][wifi:445]: - 'Transporter' [redacted]▂▄▆█
[D][wifi:446]:     Channel: 11
[D][wifi:447]:     RSSI: -33 dB
[I][wifi:445]: - 'Transporter' [redacted]▂▄▆█
[D][wifi:446]:     Channel: 1
[D][wifi:447]:     RSSI: -53 dB
[I][wifi:445]: - 'Transporter' [redacted]▂▄▆█
[D][wifi:446]:     Channel: 1
[D][wifi:447]:     RSSI: -56 dB
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[I][wifi:257]: WiFi Connecting to 'Transporter'...
[D][switch:013]: 'mmWave Sensor' Turning ON.
[D][switch:056]: 'mmWave Sensor': Sending state ON
[D][switch:013]: 'mmWave Sensor' Turning ON.
[D][switch:013]: 'mmWave Sensor' Turning ON.
[D][uart_debug:158]: >>> "sensorStartsensorStartsensorStart"
[D][uart_debug:158]: <<< "sensorStart\r\n"
[D][uart_debug:158]: <<< "sensor started already\r\n"
[D][uart_debug:158]: <<< "Error\r\n"
[D][uart_debug:158]: <<< "leapMMW:/>sensorStartsensorStart\r\n"
[D][uart_debug:158]: <<< "sensorStartsensorStart is not recognized as a CLI command\r\n"
[D][uart_debug:158]: <<< "Error\r\n"
[I][wifi:518]: WiFi Connected!
[C][wifi:362]:   Local MAC: C8:F0:9E:EF:DB:70
[C][wifi:363]:   SSID: [redacted]
[C][wifi:364]:   IP Address: 192.168.86.47
[C][wifi:366]:   BSSID: [redacted]
[C][wifi:367]:   Hostname: 'everything-presence-one-efdb70'
[C][wifi:369]:   Signal strength: -33 dB ▂▄▆█
[C][wifi:373]:   Channel: 11
[C][wifi:374]:   Subnet: 255.255.255.0
[C][wifi:375]:   Gateway: 192.168.86.1
[C][wifi:376]:   DNS1: 192.168.86.1
[C][wifi:377]:   DNS2: 0.0.0.0
[D][wifi:527]: Disabling AP...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: everything-presence-one.local:3232
[C][api:025]: Setting up Home Assistant API server...
[I][app:062]: setup() finished successfully!
[D][uart_debug:158]: <<< "leapMMW:/>"
[I][app:102]: ESPHome version 2023.3.1 compiled on Mar 27 2023, 00:33:12
[I][app:104]: Project Everything_Smart_Technology.Everything_Presence_One version 1.1.3
[C][status_led:063]: Status Led Light:
[C][status_led:064]:   Pin: GPIO32
[C][wifi:504]: WiFi:
[C][wifi:362]:   Local MAC: C8:F0:9E:EF:DB:70
[C][wifi:363]:   SSID: [redacted]
[C][wifi:364]:   IP Address: 192.168.86.47
[C][wifi:366]:   BSSID: [redacted]
[C][wifi:367]:   Hostname: 'everything-presence-one-efdb70'
[C][wifi:369]:   Signal strength: -34 dB ▂▄▆█
[C][wifi:373]:   Channel: 11
[C][wifi:374]:   Subnet: 255.255.255.0
[C][wifi:375]:   Gateway: 192.168.86.1
[C][wifi:376]:   DNS1: 192.168.86.1
[C][wifi:377]:   DNS2: 0.0.0.0
[C][logger:293]: Logger:
[C][logger:294]:   Level: DEBUG
[C][logger:295]:   Log Baud Rate: 115200
[C][logger:296]:   Hardware UART: UART0
[C][i2c.arduino:052]: I2C Bus:
[C][i2c.arduino:053]:   SDA Pin: GPIO26
[C][i2c.arduino:054]:   SCL Pin: GPIO25
[C][i2c.arduino:055]:   Frequency: 50000 Hz
[C][i2c.arduino:058]:   Recovery: bus successfully recovered
[I][i2c.arduino:068]: Results from i2c bus scan:
[I][i2c.arduino:074]: Found i2c device at address 0x70
[C][uart.arduino_esp32:108]: UART Bus 1:
[C][uart.arduino_esp32:109]:   TX Pin: GPIO13
[C][uart.arduino_esp32:110]:   RX Pin: GPIO14
[C][uart.arduino_esp32:112]:   RX Buffer Size: 256
[C][uart.arduino_esp32:114]:   Baud Rate: 115200 baud
[C][uart.arduino_esp32:115]:   Data Bits: 8
[C][uart.arduino_esp32:116]:   Parity: NONE
[C][uart.arduino_esp32:117]:   Stop bits: 1
[C][gpio.binary_sensor:015]: GPIO Binary Sensor ' mmWave'
[C][gpio.binary_sensor:015]:   Device Class: 'occupancy'
[C][gpio.binary_sensor:016]:   Pin: GPIO15
[C][gpio.binary_sensor:015]: GPIO Binary Sensor ' PIR'
[C][gpio.binary_sensor:015]:   Device Class: 'motion'
[C][gpio.binary_sensor:016]:   Pin: GPIO33
[C][template.binary_sensor:018]: Template Binary Sensor ' Occupancy'
[C][template.binary_sensor:018]:   Device Class: 'occupancy'
[C][template.switch:076]: Template Switch 'mmWave Sensor'
[C][template.switch:099]:   Restore Mode: restore defaults to OFF
[C][template.switch:060]:   Restore State: YES
[C][template.switch:061]:   Optimistic: YES
[C][template.switch:076]: Template Switch 'mmWave LED'
[C][template.switch:099]:   Restore Mode: restore defaults to OFF
[C][template.switch:060]:   Restore State: YES
[C][template.switch:061]:   Optimistic: YES
[C][template.switch:076]: Template Switch 'uart_presence_output'
[C][template.switch:099]:   Restore Mode: restore defaults to OFF
[C][template.switch:060]:   Restore State: YES
[C][template.switch:061]:   Optimistic: YES
[C][template.switch:076]: Template Switch 'uart_target_output'
[C][template.switch:099]:   Restore Mode: restore defaults to OFF
[C][template.switch:060]:   Restore State: YES
[C][template.switch:061]:   Optimistic: YES
[C][template.number:050]: Template Number 'mmWave Distance'
[C][template.number:050]:   Unit of Measurement: 'cm'
[C][template.number:051]:   Optimistic: YES
[C][template.number:052]:   Update Interval: 60.0s
[C][template.number:050]: Template Number 'mmWave Off Latency'
[C][template.number:050]:   Unit of Measurement: 'seconds'
[C][template.number:051]:   Optimistic: YES
[C][template.number:052]:   Update Interval: 60.0s
[C][template.number:050]: Template Number 'mmWave On Latency'
[C][template.number:050]:   Unit of Measurement: 'seconds'
[C][template.number:051]:   Optimistic: YES
[C][template.number:052]:   Update Interval: 60.0s
[C][template.number:050]: Template Number 'mmWave Sensitivity'
[C][template.number:051]:   Optimistic: YES
[C][template.number:052]:   Update Interval: 60.0s
[C][light:104]: Light 'ESP32 Status LED'
[C][shtcx:059]: SHTCx:
[C][shtcx:060]:   Model: SHTC3 (0887)
[C][shtcx:061]:   Address: 0x70
[C][shtcx:065]:   Update Interval: 60.0s
[C][shtcx:067]:   Temperature ' Temperature'
[C][shtcx:067]:     Device Class: 'temperature'
[C][shtcx:067]:     State Class: 'measurement'
[C][shtcx:067]:     Unit of Measurement: '°C'
[C][shtcx:067]:     Accuracy Decimals: 1
[C][shtcx:068]:   Humidity ' Humidity'
[C][shtcx:068]:     Device Class: 'humidity'
[C][shtcx:068]:     State Class: 'measurement'
[C][shtcx:068]:     Unit of Measurement: '%'
[C][shtcx:068]:     Accuracy Decimals: 1
[C][bh1750.sensor:118]: BH1750 ' Illuminance'
[C][bh1750.sensor:118]:   Device Class: 'illuminance'
[C][bh1750.sensor:118]:   State Class: 'measurement'
[C][bh1750.sensor:118]:   Unit of Measurement: 'lx'
[C][bh1750.sensor:118]:   Accuracy Decimals: 1
[C][bh1750.sensor:119]:   Address: 0x23
[E][bh1750.sensor:121]: Communication with BH1750 failed!
[C][bh1750.sensor:124]:   Update Interval: 30.0s
[D][api:102]: Accepted 192.168.86.87
[D][status_led:033]: Restoring light state OFF
[C][restart.button:017]: Restart Button 'Restart_internal'
[C][safe_mode.button:022]: Safe Mode Button 'everything-presence-one Safe Mode'
[C][safe_mode.button:022]:   Icon: 'mdi:restart-alert'
[D][api.connection:920]: Home Assistant 2023.3.4 (192.168.86.87): Connected successfully
[C][esp32_ble:214]: ESP32 BLE:
[C][esp32_ble_server:161]: ESP32 BLE Server:
[C][esp32_improv.component:215]: ESP32 Improv:
[C][esp32_improv.component:217]:   Status Indicator: 'NO'
[C][captive_portal:088]: Captive Portal:
[C][mdns:108]: mDNS:
[C][mdns:109]:   Hostname: everything-presence-one-efdb70
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: everything-presence-one.local:3232
[C][api:138]: API Server:
[C][api:139]:   Address: everything-presence-one.local:6053
[C][api:143]:   Using noise encryption: NO
[D][binary_sensor:036]: ' mmWave': Sending state ON
[D][binary_sensor:036]: ' Occupancy': Sending state ON
[C][improv_serial:032]: Improv Serial:
[D][binary_sensor:034]: ' PIR': Sending initial state OFF
[D][uart_debug:158]: <<< "\r\n"
[D][uart_debug:158]: <<< "..\\User_code\\main.c  line:232\r\n"
[D][uart_debug:158]: <<< "reset system\r\n"
[D][binary_sensor:036]: ' mmWave': Sending state OFF
[D][uart_debug:158]: <<< "             \r\n"
[D][uart_debug:158]: <<< "leapMMW:/>"
[D][shtcx:100]: Got temperature=28.16°C humidity=34.61%
[D][sensor:127]: ' Temperature': Sending state 25.15788 °C with 1 decimals of accuracy
[D][sensor:127]: ' Humidity': Sending state 39.60541 % with 1 decimals of accuracy
[D][binary_sensor:036]: ' Occupancy': Sending state OFF`

**Comment by EverythingSmartHome** [comment]
Thanks. It looks like the BH1750 isn't even being detected through the i2c scan.

Seems like a hardware problem so please reach out to support with your order number and we can arrange a replacement. Use the contact page on the shop and we will get back to you ASAP
