### ISSUE TITLE
ESPresense

### ISSUE THREAD

**Issue by chrispi68** [EverythingSmartHome/everything-presence-one#47]
Is it possible to install ESPresence as firmware? Which setting do I have to use to get the radar and the IR working?

I am a little disappointed that MQTT is not supported and I do not use Home Assistant. ESPresence has MQTT built in.

I also don't want to recompile the firmware of ESPHome just to enable MQTT.

**Comment by EverythingSmartHome** [comment]
MQTT is supported, just create your own ESPHome config.

I don't use ESPresence but last time I checked it didn't support all the necessary options and settings, it might work but you will probably be limited. But again, I haven't checked for a while.

**Comment by chrispi68** [comment]
> MQTT is supported, just create your own ESPHome config.

How can I change the ESPHome config? The device is logged into the WLAN. But I can't reach any web interface and I can't access it via SSH. I know the IP address.

**Comment by EverythingSmartHome** [comment]
You need to create a new config and upload that to the device. You can follow the instructions on the ESPHome website: 

https://esphome.io/guides/getting_started_command_line.html

Or there is videos of getting started

**Comment by chrispi68** [comment]
Sorry, this is too complicated for me. I am stuck at the first question "Are you using an ESP32 or ESP8266 platform?".

Is there a chance to get some information on which GPIOs the PIR and Radar are connected so I can set up ESPresense?

**Comment by EverythingSmartHome** [comment]
Pinout is as follows:

SDA: GPIO26
SCL: GPIO25
ESP32 LED: GPIO32
mmWave Output: GPIO15
PIR: GPIO33

**Comment by DanielWe2** [comment]
> Sorry, this is too complicated for me. I am stuck at the first question "Are you using an ESP32 or ESP8266 platform?".
> 
> Is there a chance to get some information on which GPIOs the PIR and Radar are connected so I can set up ESPresense?

the esphome yaml files used are in this repository. I think you can leave most of it as it and just add mqtt
