### ISSUE TITLE
EP1 is unable to connect to hidden WiFi networks

### ISSUE THREAD

**Issue by ColColonCleaner** [EverythingSmartHome/everything-presence-one#54]
My IoT SSID is normally hidden, I had to make it visible to connect the EP1s to it. Would like to keep it hidden for the future.

If I change the network to hidden, EP1s cannot connect to it anymore.
Keep in mind the configs are not changing on the EP1s, all I do is toggle the SSID between hidden and public and the EP1s are only able to connect to the public version.
There are 50 Shelly devices and a dozen other assorted IoT devices on this network so I think this is only a problem on the EP1 side.

What is the first thing to check so I can resolve this?

**Comment by EverythingSmartHome** [comment]
There is already a way to do this in the stock config, it's not a problem but rather an ESPHome design.

Add the following line to your EP1 config under the substitutions section:
```
substitutions:
  hidden_ssid: "true"
```

This will allow ESPHome to use fast connect, a feature described [here](https://esphome.io/components/wifi.html#configuration-variables)

**Comment by ColColonCleaner** [comment]
Understood, I'll add that option and confirm it's working. Thanks!
