### ISSUE TITLE
WiFi signal strength sensor

### ISSUE THREAD

**Issue by ColColonCleaner** [EverythingSmartHome/everything-presence-one#57]
Would be great for the EP1 to expose a WiFi signal strength (RSSI) sensor to HA. Good for debugging dead zones or interference. Shelly relays do this and it's a really nice feature to have.

Edit: I know this can be seen in the EP1 logs if directly connected but getting the sensor in HA means history logging for it, which is a benefit since trends can be noticed at different times of day/week then.

**Comment by DutchDeffy** [comment]
Hi, 
Because the EP1 is based on ESPhome, you can do this yourself. ([docs](https://esphome.io/components/sensor/wifi_signal.html)).

**Comment by ColColonCleaner** [comment]
Thanks! I should have followed up that I found it and am now using a fully custom config rather than just the substitutions. It's great that ESPHome has this available.

Would still be good to keep this issue open so it can be added to the official config. I'll open a PR if I get the chance. Thanks again!
