### ISSUE TITLE
Does the EP1 work with any USB-C cable and power adapter/phone charger?

### ISSUE THREAD

**Issue by teijiIshida** [EverythingSmartHome/everything-presence-one#59]
Does the EP1 work with any USB-C cable (USB-A to USB-C, USB-C to USB-C, USB2.0, and USB3.0) and power adapter/phone charger? Can someone recommend some known good ones on Amazon US? Thank you.

Edit: Would something [like](https://www.amazon.com/Anker-Compatible-Powerport-Wireless-Included/dp/B089477M22/ref=sr_1_50?crid=OTHNDHYY1O2I&keywords=anker+usb+c+charger&qid=1682614504&s=electronics&sprefix=anker+usb+c+charger+%2Celectronics%2C104&sr=1-50) this work with EP1?

**Comment by EverythingSmartHome** [comment]
You can use pretty much any USB charger with the EP1, the power requirements are pretty low. Anything over 500ma should suffice!

Should work with any cable, I use one on my desk with a USB-C to USB-C UGreen charger and also use other various USB-A to USB-C chargers around the house too.

**Comment by teijiIshida** [comment]
Thank you.
