### ISSUE TITLE
Webpage not loading

### ISSUE THREAD

**Issue by Necro-Chaos** [EverythingSmartHome/everything-presence-one#63]
Hi,
I just recieved 2 EP1s. When I power them up 1 red light on the mm wave sensor starts flashing but not the other light. I can connect to the WiFi network it is broadcasting, but when I try to go to 192.168.4.1 it fails on both. I have tried different browsers and on my laptop and phone.
Am I missing a step. I have also tried different power cables, and powering it through my laptop and with a wall charger.

**Comment by wollinger69** [comment]
Hi,

I see the connect button, the serial device and click to continue & overwrite the device but it stays there on the preparing to installing/Preparing installation message.

Any tips?

I tried connected to my PC and to the server running HA, same issue.
