### ISSUE TITLE
Issues connecting to network with Japanese characters

### ISSUE THREAD

**Issue by jonathan-morton** [EverythingSmartHome/everything-presence-one#68]
When using the web UI my WiFi network displays like this `å¬å®èª¿æ»åºãã³-5G` and it doesn't allow me to connect.

However when I entered it in directly as `公安調査庁バン-5G` it allowed me to connect and my network showed correctly in the logs. I think its just a front end issue.

**Comment by EverythingSmartHome** [comment]
Hi there,

I'm assuming you are in Japan (sorry if I got the country wrong) and the language is set to Japanese?

This is an ESPHome issue it looks like, if you wouldn't mind raising this as a bug in the ESPHome repo: https://github.com/esphome/issues/issues then they can hopefully implement the fix.

Thanks!
