### ISSUE TITLE
PIR sensitivity?

### ISSUE THREAD

**Issue by mavermc** [EverythingSmartHome/everything-presence-one#7]
Was curious if the Panasonic has an adjustment for this? I have an open floor concept so being able to turn it down just a smidge would probably clear up a lot of false triggers.

**Comment by EverythingSmartHome** [comment]
> Was curious if the Panasonic has an adjustment for this? I have an open floor concept so being able to turn it down just a smidge would probably clear up a lot of false triggers.

There is no way to control the sensitivity unfortunately

**Comment by mavermc** [comment]
ah damn, my brushed aluminum fridge is causing triggers outside the room. I'll have to find a better place for it. Thanks for writing back.
