### ISSUE TITLE
ESPHome reports wrong version of firmware starting with ESPHome v2023.5.2+

### ISSUE THREAD

**Issue by devinhedge** [EverythingSmartHome/everything-presence-one#70]
This has been a persistent problem.

Steps to recreate:
1. Navigate to ESPHome proper OR to the Update prompt at the top of the HA Settings page
2. Update EP1 via ESPHome OR via the HA Settings page
3. If updating via ESPHome proper, watch EP1 update and notice there are no error messages
4. EP1 successfully updates, and reboots
5. EP1 reports correct version of firmware (currently v2023.5.5) but HA and ESPHome list the installed version as v2023.5.2

Is there something that should be updating ESPHome's device catalog or registry with the correct version when EP1 reboots?

**Comment by devinhedge** [comment]
<img width="585" alt="Screenshot 2023-05-30 at 8 48 56 PM" src="https://github.com/EverythingSmartHome/everything-presence-one/assets/217600/4e83e0e4-bbdd-494d-b98d-b481947303d4">

**Comment by devinhedge** [comment]
<img width="332" alt="Screenshot 2023-05-30 at 9 43 55 PM" src="https://github.com/EverythingSmartHome/everything-presence-one/assets/217600/4cc0325c-2837-4cdc-8700-459d5974c683">

**Comment by devinhedge** [comment]
<img width="671" alt="Screenshot 2023-05-30 at 9 46 37 PM" src="https://github.com/EverythingSmartHome/everything-presence-one/assets/217600/1a99eff5-5226-45c4-b42d-25ec0c5b16f8">

It's a bit of a head-scratcher.

**Comment by elminster13** [comment]
Mine does the same thing.

**Comment by Quentame** [comment]
Rebooting HA solves the issue ?
If yes, the issue is on the HA side

**Comment by devinhedge** [comment]
It does not solve the issue. I copied off the last build log and noticed the version is being baked into the build somehow. I haven't looked at the template but I suspect something may be going on there or within any libraries it may be referencing.

**Comment by norey** [comment]
How are you able to update its firmware? I'm still on 2023.4.2. I just tried re-flashing it at https://everythingsmarthome.github.io/everything-presence-one/updating.html and the version stayed the same.

![info](https://github.com/EverythingSmartHome/everything-presence-one/assets/3504959/c8d035a9-801e-4be4-b6d1-b8286691be15)

**Comment by Quentame** [comment]
I have an EP1 on v`2023.7.1` but the update entity isn't created, so it's not even possible to try to update from HA now (may changed, need a manual update).

Seen the fw version on the device info panel.

**Comment by brofeelgood** [comment]
I noticed the same problem previously when I was updating the EP1 firmware wirelessly. For me, updating via wifi works maybe 1 out of 50 times. It would invariably time out before completion. You can see the error in the logs if you perform the update in the ESPHome add-on. If you do it via the HA prompt, it wouldn't show anything and you'd think everything's gone well when in fact it hasn't.

The foolproof way is to do it manually.
1. Go to ESPHome add-on, select the 3 dots > Install > Manual Download > Modern format and save the output file on your PC.
2. Connect EP1 to your PC via USB.
3. Open ESPHome web io (https://web.esphome.io/) on a Chrome browser.
4. Connect and select your EP1 device which should have already been detected.
5. Select Install (not Install for first time), navigate to the file downloaded in step 1 and select it.
6. Start the update and wait (2 minutes).

Anyway, I've stopped updating my EP1 firmware after firmware version 2023.7.1 because that's the version with temp/humidity calibration available in the device page and it basically covers everything I need.

**Comment by NicoLouis-be** [comment]
FYI
I added this piece of code, and it shows me the version in diagnostics as a new sensor
so it is able to read the version when you do it that way, don't get it why it's not showing it in the firmware sensor
```
text_sensor:
  - platform: version
    name: ESPHome Version
```
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/12760841/a75c5fa8-03d3-4b98-a2a0-62ba41766ff4)

![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/12760841/44299db4-0134-4c52-a318-05c81c18a0f0)

**Comment by norey** [comment]
> I have an EP1 on v`2023.7.1` but the update entity isn't created, so it's not even possible to try to update from HA now (may changed, need a manual update).
> 
> Seen the fw version on the device info panel.

what info panel?

@brofeelgood 
I only tried updating via https://everythingsmarthome.github.io/everything-presence-one/updating.html and not hass, with EP1 connected via USB.

I'm still on

```
Firmware: 2023.4.2 (Apr 28 2023, 09:31:25)
Hardware: 1.1.3
```

EP1 was integrated with the ESPHome built-in integration. No add-on was involved.

**Comment by Quentame** [comment]
> > I have an EP1 on v`2023.7.1` but the update entity isn't created, so it's not even possible to try to update from HA now (may changed, need a manual update).
> 
> > 
> 
> > Seen the fw version on the device info panel.
> 
> 
> 
> what info panel?
> 
> 
> 
> @brofeelgood 
> 
> I only tried updating via https://everythingsmarthome.github.io/everything-presence-one/updating.html and not hass, with EP1 connected via USB.
> 
> 
> 
> I'm still on
> 
> 
> 
> ```
> 
> Firmware: 2023.4.2 (Apr 28 2023, 09:31:25)
> 
> Hardware: 1.1.3
> 
> ```
> 
> 
> 
> EP1 was integrated with the ESPHome built-in integration. No add-on was involved.

In this panel:
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/14821482/a88a80e8-bbad-421a-9ae3-4faaf93c6a62)

Add-on is HA related, not ESPHome.

**Comment by norey** [comment]
> > > I have an EP1 on v`2023.7.1` but the update entity isn't created, so it's not even possible to try to update from HA now (may changed, need a manual update).
> > 
> > 
> > > 
> > 
> > 
> > > Seen the fw version on the device info panel.
> > 
> > 
> > what info panel?
> > @brofeelgood
> > I only tried updating via https://everythingsmarthome.github.io/everything-presence-one/updating.html and not hass, with EP1 connected via USB.
> > I'm still on
> > ```
> > 
> > Firmware: 2023.4.2 (Apr 28 2023, 09:31:25)
> > 
> > Hardware: 1.1.3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > EP1 was integrated with the ESPHome built-in integration. No add-on was involved.
> 
> In this panel: ![image](https://user-images.githubusercontent.com/14821482/271053343-a88a80e8-bbad-421a-9ae3-4faaf93c6a62.jpeg)
> 
> Add-on is HA related, not ESPHome.

Yeah, that image is what I posted earlier. Showing the older version.

My main question was about the method of updating EP1 to the latest version. As I mentioned before, it only updated to the 2023.4.2 version.

**Comment by brofeelgood** [comment]
> @brofeelgood I only tried updating via https://everythingsmarthome.github.io/everything-presence-one/updating.html and not hass, with EP1 connected via USB.
> 
> I'm still on
> 
> ```
> Firmware: 2023.4.2 (Apr 28 2023, 09:31:25)
> Hardware: 1.1.3
> ```
> 
> EP1 was integrated with the ESPHome built-in integration. No add-on was involved.

I'm sorry. I made the silly assumption everyone had the ESPHome add-on installed. Monitoring the logs in the add-on was how I figured out the updates were failing more often than not when done over wifi, regardless of wifi signal strength. Switching over to manual updates was what did the trick for me. I've only ever used the link you provided on initial setup.

A little more info here regarding the ESPHome add-on.

You can find it in Settings > Add-ons.
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/118669907/1b61093a-702d-46bb-bb87-0d06cc73cba7)

The options that are available after clicking on the 3 dots in the add-on.
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/118669907/8a77a173-d542-4c37-a73d-05e127006173)

What you see in ESPHome web io.
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/118669907/7273ab9d-fb7e-4ddc-a86f-e1a89bc1b0f7)

The steps to update via USB.
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/118669907/3d5b8a7e-cf63-41d9-b082-a6aa71fff963)

Here's how it looks on my EP1 device page.
![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/118669907/4d84efc7-0194-4ac8-b45f-238f483d382d)

**Comment by EverythingSmartHome** [comment]
> I noticed the same problem previously when I was updating the EP1 firmware wirelessly. For me, updating via wifi works maybe 1 out of 50 times. It would invariably time out before completion. You can see the error in the logs if you perform the update in the ESPHome add-on. If you do it via the HA prompt, it wouldn't show anything and you'd think everything's gone well when in fact it hasn't, which is why it'll ask you to update it over and over again.
> 
> The foolproof way is to do it manually.
> 
> 1. Go to ESPHome add-on, select the 3 dots > Install > Manual Download > Modern format and save the output file on your PC.
> 2. Connect EP1 to your PC via USB.
> 3. Open ESPHome web io (https://web.esphome.io/) on a Chrome browser.
> 4. Connect and select your EP1 device which should have already been detected.
> 5. Select Install (not Install for first time), navigate to the file downloaded in step 1 and select it.
> 6. Start the update and wait (2 minutes).
> 
> Anyway, I've stopped updating my EP1 firmware after version 2023.7.1 because that's the version with temp/humidity calibration available in the device page and that basically covers everything I need.

There is no need to update this way, you can do it over WiFi but you need to press the "Safe Mode" button  from the device page first - this shuts down most components and allows the WiFi update to complete. Hope that helps

**Comment by brofeelgood** [comment]
Thanks for the clarification Lewis. I always wondered what that button was about. The first (and only) time I clicked it, it wiped out all my settings and I had to set up everything again. Is that normal/expected behaviour?

**Comment by EverythingSmartHome** [comment]
> Thanks for the clarification Lewis. I always wondered what that button was about. The first (and only) time I clicked it, it wiped out all my settings and I had to set up everything again. Is that normal/expected behaviour?

It doesn't wipe out your settings but it will make everything "unavailable" until the device is restarted or flashed. All your settings and everything remain untouched. The safe mode button shuts down most components (that's why they go unavailable) so that the ESP32 doesn't get interrupted when it's doing the update over WiFi

**Comment by brofeelgood** [comment]
I'm happy to report everything made it in one attempt (via WiFi) by initiating "Safe Mode" before updating just as Lewis advised. The only minor glitch was "Safe Mode" getting cancelled halfway through the esp32 image compilation, but I quickly reactivated it and everything came through just fine, cheers.

**Comment by norey** [comment]
How do I update via wifi? I'm still confused. I see the "Safe Mode" button in the device page. What needs to be done after pressing it?

That's what I see in the device page:

<img width="1180" alt="Screenshot 2024-01-06 at 6 12 35 PM" src="https://github.com/EverythingSmartHome/everything-presence-one/assets/3504959/f195ff4f-d790-4a02-b824-cc0e14c4ccb4">
