### ISSUE TITLE
5V but any Amps ?

### ISSUE THREAD

**Issue by Quentame** [EverythingSmartHome/everything-presence-one#71]
As I understand, EP1 supports 5V, but at what amps ?
I see 20W USB-C chargers which outputs: 5V=3A/9V=2.22A/12V=1.67A
Or USB-A chargers which outputs: 5V=2.1A or other 5V=1A

Will those chargers work with EP1 without damaging it using the USB-C connector ?

I'm not that good at electrical 😅

**Comment by EverythingSmartHome** [comment]
EP1 uses around 250ma at boot and around 150 during normal operation, therefor any USB charger of 500ma or greater should be totally fine.
