### ISSUE TITLE
Hardwire switch/input

### ISSUE THREAD

**Issue by vergoossen** [EverythingSmartHome/everything-presence-one#72]
Hi,

Would it be possible, or maybe in the future. To connect a "switchline" to minimize lag?
For example to connect a wire from the device to a Shelly on the input/switch wire, which will pulse when occupancy is detected?

**Comment by EverythingSmartHome** [comment]
This would already be possible using one of the 4 spare GPIO pins on the board, just set them to be an output in the ESPHome config.
