### ISSUE TITLE
mDNS lookup failure

### ISSUE THREAD

**Issue by TomHart** [EverythingSmartHome/everything-presence-one#75]
My EP1 mDNS lookup fails, meaning ESPHome thinks the device is offline. Other ESP devices are fine. I haven't changed anything other than the temp offset, can you suggest anything to try? I've tried removing my DHCP lease, and unplugging/replugging the device in, so avail.

```bash
root@TOM-PC:/mnt/c/Windows/system32# dig esp-cam-1 +short
192.168.5.233
root@TOM-PC:/mnt/c/Windows/system32# dig esp-cam-1.lan +short
192.168.5.233
root@TOM-PC:/mnt/c/Windows/system32# dig esp-cam-1.local +short
192.168.5.233
root@TOM-PC:/mnt/c/Windows/system32# dig everything-presence-one-707ec8 +short
192.168.1.98
root@TOM-PC:/mnt/c/Windows/system32# dig everything-presence-one-707ec8.lan +short
192.168.1.98
root@TOM-PC:/mnt/c/Windows/system32# dig everything-presence-one-707ec8.local +short
root@TOM-PC:/mnt/c/Windows/system32#
```

**Comment by TomHart** [comment]
Still having this issue, has anyone else noticed it too?

**Comment by EverythingSmartHome** [comment]
So sorry for not getting back to you, somehow I missed this issue. This would be more of a ticket for ESPHome as the EP1 doesn't do anything special here - if it is still an issue for you.

**Comment by TomHart** [comment]
No worries! Cheers :)
