### ISSUE TITLE
Installation without WebUSB?

### ISSUE THREAD

**Issue by Ocramius** [EverythingSmartHome/everything-presence-one#77]
I'm running Linux (Ubuntu 20.04) and trying to set up the EP1.

I've immediately run in a few problems:

 * Firefox does not support WebUSB (by their correct choice, TBH)
 * Chromium runs inside Snap, so it is prevented from accessing USB devices by Apparmor
 * Google Chrome (which I installed after trying everything else: I really don't want google software on my device) can't access `/dev/tty*`, see #28

I was wondering if there was a simpler way to install the EP1 firmware, perhaps via a terminal command instead?

Effectively thinking of an alternative to what is listed on this page: https://github.com/EverythingSmartHome/everything-presence-one/blob/9719987cc72c7588916cca5a9268d34e8406171c/static/updating.md#everything-presence-one-esphome-firmware-install

A link would suffice, if there is a clear/known methodology that doesn't involve a browser, and all its complex underlying tech stack :D

**Comment by Ocramius** [comment]
BTW: I managed to install the EP1, I just can't wait to uninstall Google Chrome :D

**Comment by EverythingSmartHome** [comment]
Sure, you can use esphome-flasher for example: https://github.com/esphome/esphome-flasher or use esptool (which is the native tool everything uses under the hood): https://github.com/espressif/esptool

**Comment by Ocramius** [comment]
Excellent! Giving it a try, then contributing to the docs :-)

**Comment by Ocramius** [comment]
Hmm, where is the pre-compiled binary that is being loaded by the webpage?

I tried tracking it down through https://unpkg.com/esp-web-tools@9.0.3/dist/web/connect-3e6b1f54.js (and previously https://unpkg.com/esp-web-tools@9.0.3/dist/web/install-button.js?module ), but I can't seem to find a clear reference.

**Comment by EverythingSmartHome** [comment]
You mean this one? https://github.com/EverythingSmartHome/everything-presence-one/blob/f42a532e3d55d51751a4d9ed12ad84ed99dcf159/everything-presence-one-esp32/everything-presence-one-esp32.bin

**Comment by Ocramius** [comment]
Before I brick everything, I suppose the procedure would be as follows:

```sh
wget https://github.com/EverythingSmartHome/everything-presence-one/blob/f42a532e3d55d51751a4d9ed12ad84ed99dcf159/everything-presence-one-esp32/everything-presence-one-esp32.bin

# Is there a boot loader, or is this the binary that goes to address zero?
 # obviously port depends on environment:
esptool.py \
  --port /dev/ttyUSB2 \
  write_flash 0 ./everything-presence-one-esp32.bin

# At this stage, there should be some serial connection, to configure WiFi, right?
```

**Comment by EverythingSmartHome** [comment]
To flash the firmware, you would do something like this (not on Linux at the moment so can't verify):
```
esptool.py --port /dev/ttyUSB2 --baud 460800 --before default_reset write_flash -z --flash_size detect 0x0 everything-presence-one-esp32.bin --erase-all
```

As for WiFi, once flashed you should be able to connect to the AP that will show up, which will then allow you to connect to your own WiFi.

**Comment by Ocramius** [comment]
Note to self: complete this guide at the next EP1 purchase 😁

Yes, I was lazy, installed chrome, then uninstalled it: workable solution, for now, but not a good one.
