### ISSUE TITLE
Bluetooth broadcasting

### ISSUE THREAD

**Issue by norey** [EverythingSmartHome/everything-presence-one#78]
I was pairing a headphones to my phone and found `everything-pr-xxxxxx` in the bluetooth available devices list. Why is it broadcasting by default? is this a known thing? I'm not much familiar with ESPhome. The EP1 is connected to Home Assistant and running fine. I thought that maybe I can login to the ESPhome web UI on the EP1 and see what's happening but there is no web service on the EP1.

**Comment by wila91** [comment]
My sensors are also broadcasting for some reason. Dont think that Bluetooth should be broadcasting... Any ideas why and how to stop it?

**Comment by siparker** [comment]
it is probably the esp32_improv component as that allows credentials update over bluetooth i think? https://esphome.io/components/esp32_improv.html

**Comment by EverythingSmartHome** [comment]
Fixed with dedicated Bluetooth and non-bluetooth builds.
