### ISSUE TITLE
Not all Configuration entities are available

### ISSUE THREAD

**Issue by Iraijus** [EverythingSmartHome/everything-presence-one#90]
Greetings. When going through the documentation, I noticed that I should have a few more configuration options available to me than I currently do.
![Screenshot_20230727_091822](https://github.com/EverythingSmartHome/everything-presence-one/assets/77201332/b26b4bf7-46a7-49de-95f7-0bf539f5d253)

I have reinstalled the firmware a few times and am currently running the beta firmware, but I did have the exact same problem with the most recent stable version.

**Comment by EverythingSmartHome** [comment]
Hello, which options are you looking for that are missing?

**Comment by Iraijus** [comment]
Thank you for the quick response! As you can see in the screenshot, there are 5 entities that are unavailable. This is what I meant in my previous message. They do show up, but the HA entities are unavailable, so I cannot configure/use them. Are they supposed to be available, or did I misunderstand this part?

**Comment by EverythingSmartHome** [comment]
Ah, this is just a Home Assistant feature. Simply click on the entity that is unavailable, click settings and then enable it and press save.

**Comment by Iraijus** [comment]
Now I feel a bit stupid. I knew about the disabling feature, of course, but I have never seen auto-disabled entities that were not disabled because of problems with my devices. Good to know that this can happen. Thank you!
